---

    - name: ensure apt packages are present
      become: true
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - nginx
        - sqlite3
        - python3
        - python3-dev
        - python3-setuptools
        - python3-pip
        - uwsgi
        - uwsgi-plugin-python3
        - rsync

    - name: ensure pip3 packages are present
      become: true
      pip:
        name: "{{ item }}"
        executable: pip3
      loop:
        - django
        - djangorestframework
        - markdown
        - django-filter
        - django-cors-headers
