---
- name: ensure /home/{{ ansible_user }}/.ssh/ exists
  file:
    path: /home/{{ ansible_user }}/.ssh
    state: directory
    mode: 0700

- name: put the client key in authorized_keys
  copy:
    src: "{{ hostvars[groups['nanopis'][0]]['ssh_public_key_src'] }}"
    dest: /home/{{ ansible_user }}/.ssh/authorized_keys
    mode: 0600

- name: copy management public key
  copy:
    src: "{{ ssh_public_key_src }}"
    dest: /home/{{ ansible_user }}/.ssh/id_rsa.pub
    mode: 0644

- name: copy management private key
  copy:
    src: "{{ ssh_private_key_src }}"
    dest: /home/{{ ansible_user }}/.ssh/id_rsa
    mode: 0600

- name: ensure line "ClientAliveInterval 4" is in sshd_config
  become: true
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^ClientAliveInterval "
    line: "ClientAliveInterval 4"

- name: restart sshd
  become: true
  systemd:
    name: sshd
    enabled: true
    state: restarted
    daemon_reload: yes
