---
- name: ensure apt packages are present
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - iperf3
    - python3
    - python3-dev
    - python3-setuptools
    - python3-pip

- name: ensure pip3 packages are present
  become: true
  pip:
    name: "{{ item }}"
    executable: pip3
  loop:
    - twisted
