---
- name: deploys the management server
  hosts: uberserve
  vars:
    container_name: livinglab-management-server
  tasks:

    - name: ensure docker is on the server
      apt:
        name: docker.io
        state: present

    - name:
