---
- name: deploy the iperf3-mux server
  hosts: management
  tasks:

    - name: ensure apt packages are present
      become: true
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - iperf3
        - python3
        - python3-dev
        - python3-setuptools
        - python3-pip

    - name: ensure pip3 packages are present
      become: true
      pip:
        name: "{{ item }}"
        executable: pip3
      loop:
        - twisted

    - name: create testing-server folder
      file:
        path: /home/adam/testing-server
        state: directory

    - name: copy server.py to server
      copy:
        src: server.py
        dest: /home/adam/testing-server/server.py

    - name: copy sockperf to server
      copy:
        src: sockperf
        dest: /home/adam/testing-server/sockperf
        mode: 0775

    - name: copy iperf3-server.service to /etc/systemd/system/iperf3-server.service
      become: true
      copy:
        src: iperf3-server.service
        dest: /etc/systemd/system/iperf3-server.service
        mode: 0777

    - name: copy sockperf-server.service to /etc/systemd/system/sockperf-server.service
      become: true
      copy:
        src: sockperf-server.service
        dest: /etc/systemd/system/sockperf-server.service
        mode: 0777

    - name: activate iperf3-server service
      become: true
      systemd:
        name: iperf3-server
        enabled: true
        state: restarted
        daemon_reload: true

    - name: activate sockperf-server service
      become: true
      systemd:
        name: sockperf-server
        enabled: true
        state: restarted
        daemon_reload: true
