---
- name: ensure apt packages are present
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - iperf3
    - python3
    - python3-pip
    - python3-dev
    - python3-setuptools
      
- name: ensure pip3 packages are present
  become: true
  pip:
    name: "{{ item }}"
    state: latest
    executable: pip3
  loop:
    - pip
    - setuptools
    - wheel
    - requests
    - iperf3
    - apscheduler
    - maya
